<!-- twoslash: { theme: "dark-plus" } -->
<p>// Auto-generated by the twoslash-cli
import React from "react"</p>
<p>const innerHTML = <code> // codefence: {1} function greet(person: string, date: Date) {   console.log(</code>Hello ${person}, today is ${date.toDateString()}!`)
}</p>
<p>greet("Maddison", new Date())</p>
<p>`</p>
<p>export const Code = () => &#x3C;pre className='{1}' dangerouslySetInnerHTML={{ __html: innerHTML }} /></p>