<!-- twoslash: { themes: ["nord", "light-plus"] } -->
<p>// Auto-generated by the twoslash-cli
import React from "react"</p>
<p>const innerHTML = <code>const a = 123 const b = 3456</code></p>
<p>export const Code = () => &#x3C;pre className='' dangerouslySetInnerHTML={{ __html: innerHTML }} /></p>