<p>// Auto-generated by the twoslash-cli
import React from "react"</p>
<p>const innerHTML = <code>const abc = 123 const cvfd = "1231"</code></p>
<p>export const Code = () => &#x3C;pre className='' dangerouslySetInnerHTML={{ __html: innerHTML }} /></p>