import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <article className={styles.red}>
          <div className={styles.intro}>
            <p>The documentation concerning the npm modules of</p>
            <h1 className={styles.title}>Shiki-Twoslash</h1>
            <p>
              In which markdown code samples are powered by
              <br />
              the syntax engine of Visual Studio Code
              <br />
              mixed with the TypeScript compiler’s information.
            </p>
          </div>

          <div style={{ textAlign: "center" }}>
            <img src="/svgs/squiggle.svg" alt="Vercel Logo" width={70} height={25.5} />
          </div>

          <div className={styles.intro}>
            <p>By orta therox</p>
            <p>
              Purveyor of renound open source code
              <br />
              and TypeScript compiler team member
            </p>
          </div>

          <div style={{ textAlign: "center" }}>
            <img src="/svgs/logo.svg" alt="Vercel Logo" width={167} height={238} />
          </div>
        </article>
      </main>
    </div>
  );
}
